name: idd-manuscripts
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.11
  - pip

  # Data Science Core
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10

  # Visualization
  - matplotlib>=3.7
  - seaborn>=0.12
  - plotly>=5.14
  - altair>=5.0

  # Documentation & Publishing
  - quarto>=1.4
  - pandoc>=3.1
  - jupyter>=1.0
  - nbconvert>=7.0
  - sphinx>=6.0
  - sphinxcontrib-bibtex>=2.5

  # Development Tools
  - black>=23.0
  - flake8>=6.0
  - mypy>=1.0
  - pre-commit>=3.0
  - pytest>=7.0
  - pytest-cov>=4.0

  # Optional: Statistical/Scientific Computing
  - statsmodels>=0.14
  - scikit-learn>=1.3
  - networkx>=3.0

  # Optional: R integration (if needed)
  - r-base>=4.3
  - r-essentials
  - rpy2>=3.5

  # Pip-only packages
  - pip:
    - python-docx>=0.8.11
    - sphinx-book-theme>=1.0.1
    - myst-parser>=2.0.0
    - jupytext>=1.15.0
    - nbsphinx>=0.9.0
    - sphinx-external-toc>=1.0.0
    - cookiecutter>=2.1.1
    - rich>=13.0.0
